"""Email reporter — sends scan results via SMTP with STARTTLS."""

import logging
import os
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Any

logger = logging.getLogger(__name__)


def send_email_report(
    findings: list[dict[str, Any]],
    repos_scanned: list[dict[str, Any]],
    markdown_content: str | None = None,
) -> bool:
    """Send scan report via email using SMTP with STARTTLS.

    Only sends if all required SMTP env vars are configured.
    Failures are logged but do not raise — email is best-effort.

    Args:
        findings: List of all findings from the scan.
        repos_scanned: List of repo dicts that were scanned.
        markdown_content: Optional markdown report content to include.

    Returns:
        True if email was sent successfully, False otherwise.
    """
    smtp_host = os.environ.get("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    smtp_user = os.environ.get("SMTP_USER", "")
    smtp_pass = os.environ.get("SMTP_PASS", "")
    alert_email = os.environ.get("ALERT_EMAIL", "")

    if not smtp_user or not smtp_pass or not alert_email:
        logger.warning(
            "Email reporting skipped — SMTP_USER, SMTP_PASS, and ALERT_EMAIL must all be set"
        )
        return False

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    total = len(findings)
    subject = f"Security Scan Report — {now} — {total} findings"

    body = _build_email_body(findings, repos_scanned, markdown_content)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = alert_email
    msg.attach(MIMEText(body, "plain", "utf-8"))

    # If we have markdown, also attach as HTML-ish plain text
    if markdown_content:
        msg.attach(MIMEText(markdown_content, "plain", "utf-8"))

    try:
        logger.info("Sending email report to %s via %s:%d", alert_email, smtp_host, smtp_port)
        with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, [alert_email], msg.as_string())
        logger.info("Email report sent successfully")
        return True
    except Exception as e:
        logger.error("Failed to send email report: %s", e)
        return False


def _build_email_body(
    findings: list[dict[str, Any]],
    repos_scanned: list[dict[str, Any]],
    markdown_content: str | None = None,
) -> str:
    """Build plain-text email body with scan summary.

    Args:
        findings: All findings from the scan.
        repos_scanned: All repos that were scanned.
        markdown_content: Optional full markdown report.

    Returns:
        Plain-text email body.
    """
    lines: list[str] = []
    lines.append("Repository Security Scan Report")
    lines.append("=" * 40)
    lines.append("")
    lines.append(f"Scan Date: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"Repositories Scanned: {len(repos_scanned)}")
    lines.append(f"Total Findings: {len(findings)}")
    lines.append("")

    # Severity breakdown
    from collections import Counter
    severity_counts = Counter(f.get("severity", "unknown") for f in findings)
    if severity_counts:
        lines.append("Severity Breakdown:")
        for sev in ["critical", "high", "medium", "low"]:
            count = severity_counts.get(sev, 0)
            if count > 0:
                lines.append(f"  {sev.capitalize()}: {count}")
        lines.append("")

    # Tool breakdown
    tool_counts = Counter(f.get("tool", "gitleaks") for f in findings)
    if tool_counts:
        lines.append("Findings by Tool:")
        for tool, count in sorted(tool_counts.items()):
            lines.append(f"  {tool}: {count}")
        lines.append("")

    # Top findings
    critical_high = [f for f in findings if f.get("severity") in ("critical", "high")]
    if critical_high:
        lines.append("Critical/High Findings:")
        lines.append("-" * 30)
        for f in critical_high[:20]:
            lines.append(f"  [{f.get('severity', '').upper()}] {f.get('repo', '')} — {f.get('description', '')}")
            lines.append(f"    File: {f.get('file', 'N/A')} Line: {f.get('line', 'N/A')}")
            lines.append("")

    if markdown_content:
        lines.append("")
        lines.append("Full Report:")
        lines.append("=" * 40)
        lines.append(markdown_content)

    lines.append("")
    lines.append("---")
    lines.append("Generated by repo-security-scanner")

    return "\n".join(lines)
